package com.example.api.controller;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class controller {
    List<Name> dbnames = new ArrayList<>();

    public void insertDbNames(){
        //Nomes masculinos
        dbnames.add(new Name(1,"Antonio",1));
        dbnames.add(new Name(1, "Almeida", 1));
        dbnames.add(new Name(2, "Antônio", 1));
        dbnames.add(new Name(3, "Arthur", 1));
        dbnames.add(new Name(4, "Barbosa", 1));
        dbnames.add(new Name(5, "Bernardo", 1));
        dbnames.add(new Name(6, "Benjamin", 1));
        dbnames.add(new Name(7, "Carlos", 1));
        dbnames.add(new Name(8, "Caio", 1));
        dbnames.add(new Name(9, "Cristiano", 1));
        dbnames.add(new Name(10, "Daniel", 1));
        dbnames.add(new Name(11, "Diego", 1));
        dbnames.add(new Name(12, "Davi", 1));
        dbnames.add(new Name(13, "Eduardo", 1));
        dbnames.add(new Name(14, "Elias", 1));
        dbnames.add(new Name(15, "Erick", 1));
        dbnames.add(new Name(16, "Felipe", 1));
        dbnames.add(new Name(17, "Fernando", 1));
        dbnames.add(new Name(18, "Francisco", 1));
        dbnames.add(new Name(19, "Gabriel", 1));
        dbnames.add(new Name(20, "Gustavo", 1));
        dbnames.add(new Name(21, "Guilherme", 1));
        dbnames.add(new Name(22, "Henrique", 1));
        dbnames.add(new Name(23, "Heitor", 1));
        dbnames.add(new Name(24, "Hugo", 1));
        dbnames.add(new Name(25, "Igor", 1));
        dbnames.add(new Name(26, "Isaías", 1));
        dbnames.add(new Name(27, "Ivan", 1));
        dbnames.add(new Name(28, "João", 1));
        dbnames.add(new Name(29, "José", 1));
        dbnames.add(new Name(30, "Júlio", 1));
        dbnames.add(new Name(31, "Kaio", 1));
        dbnames.add(new Name(32, "Kevin", 1));
        dbnames.add(new Name(33, "Kauã", 1));
        dbnames.add(new Name(34, "Leonardo", 1));
        dbnames.add(new Name(35, "Lucas", 1));
        dbnames.add(new Name(36, "Luís", 1));
        dbnames.add(new Name(37, "Marcos", 1));
        dbnames.add(new Name(38, "Matheus", 1));
        dbnames.add(new Name(39, "Miguel", 1));
        dbnames.add(new Name(40, "Natanael", 1));
        dbnames.add(new Name(41, "Nelson", 1));
        dbnames.add(new Name(42, "Nicolas", 1));
        dbnames.add(new Name(43, "Orlando", 1));
        dbnames.add(new Name(44, "Otávio", 1));
        dbnames.add(new Name(45, "Osmar", 1));
        dbnames.add(new Name(46, "Paulo", 1));
        dbnames.add(new Name(47, "Patrick", 1));
        dbnames.add(new Name(48, "Pedro", 1));
        dbnames.add(new Name(49, "Quentin", 1));
        dbnames.add(new Name(50, "Quirino", 1));
        dbnames.add(new Name(51, "Quinto", 1));
        dbnames.add(new Name(52, "Rafael", 1));
        dbnames.add(new Name(53, "Ricardo", 1));
        dbnames.add(new Name(54, "Rodrigo", 1));
        dbnames.add(new Name(55, "Samuel", 1));
        dbnames.add(new Name(56, "Sebastião", 1));
        dbnames.add(new Name(57, "Sérgio", 1));
        dbnames.add(new Name(58, "Tiago", 1));
        dbnames.add(new Name(59, "Tomás", 1));
        dbnames.add(new Name(60, "Túlio", 1));
        dbnames.add(new Name(61, "Urias", 1));
        dbnames.add(new Name(62, "Ulisses", 1));
        dbnames.add(new Name(63, "Uriel", 1));
        dbnames.add(new Name(64, "Vicente", 1));
        dbnames.add(new Name(65, "Victor", 1));
        dbnames.add(new Name(66, "Vinícius", 1));
        dbnames.add(new Name(67, "Wagner", 1));
        dbnames.add(new Name(68, "Wallace", 1));
        dbnames.add(new Name(69, "William", 1));
        dbnames.add(new Name(70, "Xavier", 1));
        dbnames.add(new Name(71, "Xisto", 1));
        dbnames.add(new Name(72, "Xerxes", 1));
        dbnames.add(new Name(73, "Yago", 1));
        dbnames.add(new Name(74, "Yan", 1));
        dbnames.add(new Name(75, "Yuri", 1));
        dbnames.add(new Name(76, "Zacarias", 1));
        dbnames.add(new Name(77, "Zair", 1));
        dbnames.add(new Name(78, "Zeca", 1));
        //Nomes femininos
        dbnames.add(new Name(1,"Alicia",0));
        dbnames.add(new Name(2,"Amanda",0));
        dbnames.add(new Name(3,"Ana",0));
        dbnames.add(new Name(4,"Beatriz",0));
        dbnames.add(new Name(5,"Bianca",0));
        dbnames.add(new Name(6,"Bruna",0));
        dbnames.add(new Name(7,"Camila",0));
        dbnames.add(new Name(8,"Carla",0));
        dbnames.add(new Name(9,"Caroline",0));
        dbnames.add(new Name(10,"Catarina",0));
        dbnames.add(new Name(11,"Cláudia",0));
        dbnames.add(new Name(12,"Daniele",0));
        dbnames.add(new Name(13,"Debora",0));
        dbnames.add(new Name(14,"Eduarda",0));
        dbnames.add(new Name(15,"Elisa",0));
        dbnames.add(new Name(16,"Fernanda",0));
        dbnames.add(new Name(17,"Flávia",0));
        dbnames.add(new Name(18,"Gabriela",0));
        dbnames.add(new Name(19,"Giovanna",0));
        dbnames.add(new Name(20,"Helena",0));
        dbnames.add(new Name(21,"Isabela",0));
        dbnames.add(new Name(22,"Jéssica",0));
        dbnames.add(new Name(23,"Juliana",0));
        dbnames.add(new Name(24,"Karla",0));
        dbnames.add(new Name(25,"Larissa",0));
        dbnames.add(new Name(26,"Letícia",0));
        dbnames.add(new Name(27,"Lúcia",0));
        dbnames.add(new Name(28,"Luana",0));
        dbnames.add(new Name(29,"Luiza",0));
        dbnames.add(new Name(30,"Manuela",0));
        dbnames.add(new Name(31,"Mariana",0));
        dbnames.add(new Name(32,"Martha",0));
        dbnames.add(new Name(33,"Micaela",0));
        dbnames.add(new Name(34,"Natália",0));
        dbnames.add(new Name(35,"Nicole",0));
        dbnames.add(new Name(36,"Patrícia",0));
        dbnames.add(new Name(37,"Rafaela",0));
        dbnames.add(new Name(38,"Renata",0));
        dbnames.add(new Name(39,"Roberta",0));
        dbnames.add(new Name(40,"Sandra",0));
        dbnames.add(new Name(41,"Sara",0));
        dbnames.add(new Name(42,"Sofia",0));
        dbnames.add(new Name(43,"Tatiane",0));
        dbnames.add(new Name(44,"Thais",0));
        dbnames.add(new Name(45,"Valentina",0));
        dbnames.add(new Name(46,"Vanessa",0));
        dbnames.add(new Name(47,"Vera",0));
        dbnames.add(new Name(48,"Vitória",0));
        dbnames.add(new Name(49,"Yasmin",0));
        dbnames.add(new Name(50,"Zélia",0));
                
    }

}